export const SET_IS_AUTHED = 'SET_IS_AUTHED';
export const SET_SHOW_AUTH_MODAL = 'SET_SHOW_AUTH_MODAL';
export const SET_SHOW_PAYMENT_MODAL = 'SET_SHOW_PAYMENT_MODAL';
export const SET_SHOW_BALANCE_MODAL = 'SET_SHOW_BALANCE_MODAL';
export const SET_AUTH_LOGIN_TYPE = 'SET_AUTH_LOGIN_TYPE';
